server:
  port: 1010
  servlet:
    context-path: /SCSE@hbut

spring:
  data:
    mongodb:
      # URI方式配置（推荐）
      uri: mongodb://127.0.0.1:27017/msi?connectTimeoutMS=50000
      # 或拆分属性配置：
      # host: 127.0.0.1
      # port: 27017
      # database: msi
      # connect-timeout: 50000  # 毫秒，短横线命名

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.mongodb.client: DEBUG

knife4j:
  enable: true
  openapi:
    title: MSI后台测试
    description: "MSI后台测试"
    concat: 信息化建设小组